name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-group: [sanity, smoke, regression]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Allure
      run: npm install -g allure-commandline --save-dev

    - name: Run Playwright ${{ matrix.test-group }} tests
      run: npm run test:${{ matrix.test-group }}
      continue-on-error: true

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean
        echo "Allure report generated"

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.test-group }}
        path: allure-results/
        retention-days: 30

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.test-group }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{ matrix.test-group }}
        path: allure-report/
        retention-days: 30

    - name: Test Summary
      if: always()
      run: |
        echo "::group::Test Results Summary"
        echo "Test Group: ${{ matrix.test-group }}"
        echo "Status: ${{ job.status }}"
        echo "::endgroup::"