name: Playwright Tests

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Run Playwright Tests
      - name: Run Playwright tests
        run: npx playwright test

      # 6. Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          allure open allure-results

      # 7. Upload Playwright Report as artifact
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # 8. Upload Allure Report as artifact (optional)
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-results/
          retention-days: 30
